language: php

before_script:
  - sudo apt-get install build-essential zip
  - sudo easy_install sphinx
  - wget http://ftp.gnu.org/gnu/tar/tar-1.26.tar.gz
  - sh -c "tar xzvf tar-1.26.tar.gz && cd tar-1.26 && ./configure && make && sudo make install"
  - sudo ln -s /usr/local/bin/tar /usr/local/bin/gnutar
  - /usr/local/bin/gnutar --version
  - sudo ln -s /bin/tar /usr/local/bin/bsdtar
  - composer install --dev --prefer-source

env:
  - ZIPPY_ADAPTER=ZipAdapter
  - ZIPPY_ADAPTER=ZipExtensionAdapter
  - ZIPPY_ADAPTER=GNUTar\\TarGNUTarAdapter
  - ZIPPY_ADAPTER=GNUTar\\TarGzGNUTarAdapter
  - ZIPPY_ADAPTER=GNUTar\\TarBz2GNUTarAdapter
  - ZIPPY_ADAPTER=BSDTar\\TarBSDTarAdapter
  - ZIPPY_ADAPTER=BSDTar\\TarGzBSDTarAdapter
  - ZIPPY_ADAPTER=BSDTar\\TarBz2BSDTarAdapter

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit -v --coverage-text
  - phpunit -v -c phpunit-functional.xml.dist
  - sh -c "cd docs && make clean && make html"
