language: php

sudo: required

env:
  - ZIPPY_ADAPTER=ZipAdapter
  - ZIPPY_ADAPTER=ZipExtensionAdapter
  - ZIPPY_ADAPTER=GNUTar\\TarGNUTarAdapter
  - ZIPPY_ADAPTER=GNUTar\\TarGzGNUTarAdapter
  - ZIPPY_ADAPTER=GNUTar\\TarBz2GNUTarAdapter
  - ZIPPY_ADAPTER=BSDTar\\TarBSDTarAdapter
  - ZIPPY_ADAPTER=BSDTar\\TarGzBSDTarAdapter
  - ZIPPY_ADAPTER=BSDTar\\TarBz2BSDTarAdapter

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - sudo apt-get install bsdtar zip
  - npm install connect serve-static
  - ./tests/bootstrap.sh start
  - composer update --prefer-source --no-interaction
  - composer require phpunit/phpunit --update-with-dependencies --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit -v
  - ./vendor/bin/phpunit -v -c phpunit-functional.xml.dist

after_script:
  - ./tests/bootstrap.sh stop
